Vagrant.configure("2") do |config|
    # Configuración de las máquinas virtuales
    # -------------------------------------------------------
  
    # Máquina web1
    config.vm.define "web1" do |web1|
      web1.vm.box = "ubuntu/jammy64"  # Puedes cambiar la caja si deseas otra versión de Ubuntu
      web1.vm.hostname = "web1"
      web1.vm.network "private_network", ip: "192.168.56.11"
      web1.vm.provider "virtualbox" do |vb|
        vb.memory = "512"
        vb.cpus = 1
      end
      web1.vm.provision "shell", inline: <<-SHELL
        sudo apt-get update
        sudo apt-get install -y apache2
        sudo rm -rf /var/www/html
        sudo ln -fs /vagrant/web1 /var/www/html
      SHELL
    end
  
    # Máquina web2
    config.vm.define "web2" do |web2|
      web2.vm.box = "ubuntu/jammy64"
      web2.vm.hostname = "web2"
      web2.vm.network "private_network", ip: "192.168.56.12"
      web2.vm.provider "virtualbox" do |vb|
        vb.memory = "512"
        vb.cpus = 1
      end
      web2.vm.provision "shell", inline: <<-SHELL
        sudo apt-get update
        sudo apt-get install -y apache2
        sudo rm -rf /var/www/html
        sudo ln -fs /vagrant/web2 /var/www/html
      SHELL
    end
  
    # Máquina loadbalancer
    config.vm.define "loadbalancer" do |lb|
      lb.vm.box = "ubuntu/jammy64"
      lb.vm.hostname = "loadbalancer"
      lb.vm.network "private_network", ip: "192.168.56.10"
      lb.vm.provider "virtualbox" do |vb|
        vb.memory = "512"
        vb.cpus = 1
      end
      lb.vm.provision "shell", inline: <<-SHELL
        sudo apt-get update
        sudo apt-get install -y nginx
        sudo tee /etc/nginx/conf.d/load_balancer.conf > /dev/null <<EOL
  upstream backend {
      server 192.168.56.11;
      server 192.168.56.12;
  }
  
  server {
      listen 80;
      location / {
          proxy_pass http://backend;
      }
  }
  EOL
        sudo nginx -t
        sudo systemctl restart nginx
      SHELL
    end
  end
  