name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout el repositorio
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Configurar la clave SSH
      - name: Set up SSH key
        run: |
          # Guardar el secreto SSH en el archivo id_rsa
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          # Establecer los permisos correctos
          chmod 600 ~/.ssh/id_rsa
          # Configurar la autenticación SSH para evitar advertencias
          ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts

      # 3. Realizar el despliegue, por ejemplo, ejecutar un comando remoto
      - name: Deploy to server
        run: |
          ssh -o StrictHostKeyChecking=no user@your_server "deploy_script.sh"
